
export const TELANGANA_COLLEGES = [
  "Amrita Vishwa Vidyapeetham, Amaravati",
  "Amrita Vishwa Vidyapeetham, Amritapuri",
  "Amrita Vishwa Vidyapeetham, Bengaluru",
  "Amrita Vishwa Vidyapeetham, Chennai",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Amrita Vishwa Vidyapeetham, Faridabad",
  "Amrita Vishwa Vidyapeetham, Kochi",
  "Amrita Vishwa Vidyapeetham, Mysore",
  "Anurag University, Ghatkesar",
  "BVRIT Hyderabad College of Engineering for Women",
  "BVRIT Narsapur (Padmasri Dr. B.V. Raju Institute of Technology)",
  "Bharat Institute of Engineering and Technology, Ibrahimpatnam",
  "BITS Pilani, Hyderabad Campus",
  "C.V.R. College of Engineering, Ibrahimpatnam",
  "Chaitanya Bharathi Institute of Technology (CBIT), Hyderabad",
  "CMR College of Engineering & Technology, Kandlakoya",
  "CMR Institute of Technology (CMRIT), Hyderabad",
  "CMR Technical Campus, Kandlakoya",
  "Deccan College of Engineering and Technology, Hyderabad",
  "G. Narayanamma Institute of Technology and Science (GNITS)",
  "Geethanjali College of Engineering and Technology, Keesara",
  "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET)",
  "Guru Nanak Institutions Technical Campus, Ibrahimpatnam",
  "Gyan Ganga Institute of Technology",
  "Indian Institute of Technology (IIT), Hyderabad",
  "International Institute of Information Technology (IIIT), Hyderabad",
  "Jawaharlal Nehru Technological University, Hyderabad (JNTUH)",
  "JNTUH College of Engineering, Jagtial",
  "JNTUH College of Engineering, Manthani",
  "JNTUH College of Engineering, Sultanpur",
  "Kakatiya Institute of Technology and Science (KITS), Warangal",
  "Kakatiya University, Warangal",
  "Keshav Memorial Institute of Technology (KMIT), Hyderabad",
  "Lords Institute of Engineering and Technology, Hyderabad",
  "Mahatma Gandhi Institute of Technology (MGIT), Hyderabad",
  "Mahatma Gandhi University, Nalgonda",
  "Mahindra University, Hyderabad",
  "Malla Reddy College of Engineering and Technology (MRCET)",
  "Malla Reddy Engineering College (MREC), Maisammaguda",
  "Malla Reddy Institute of Technology and Science",
  "Matrusri Engineering College, Saidabad",
  "Maturi Venkata Subba Rao (MVSR) Engineering College",
  "Methodist College of Engineering and Technology, Abids",
  "Muffakham Jah College of Engineering and Technology (MJCET)",
  "National Institute of Technology (NIT), Warangal",
  "Osmania University (OU), Hyderabad",
  "Palamuru University, Mahabubnagar",
  "Satavahana University, Karimnagar",
  "SR University, Warangal",
  "Sridevi Women's Engineering College, Vattinagulapally",
  "Sreenidhi Institute of Science and Technology (SNIST), Ghatkesar",
  "St. Martin's Engineering College, Secunderabad",
  "Stanley College of Engineering and Technology for Women",
  "Telangana University, Nizamabad",
  "TKR College of Engineering and Technology, Meerpet",
  "University College of Engineering (OU), Hyderabad",
  "Vardhaman College of Engineering, Shamshabad",
  "Vasavi College of Engineering, Hyderabad",
  "Vellore Institute of Technology (VIT), Andhra Pradesh",
  "Vellore Institute of Technology (VIT), Bhopal",
  "Vellore Institute of Technology (VIT), Chennai",
  "Vellore Institute of Technology (VIT), Vellore",
  "Vidya Jyothi Institute of Technology (VJIT), Moinabad",
  "VNR Vignana Jyothi Institute of Engineering and Technology (VNRVJIET)",
  "Woxsen University, Sangareddy"
].sort();
