
export const TELANGANA_COLLEGES = [
  "Jawaharlal Nehru Technological University, Hyderabad (JNTUH)",
  "Osmania University (OU), Hyderabad",
  "National Institute of Technology (NIT), Warangal",
  "Indian Institute of Technology (IIT), Hyderabad",
  "International Institute of Information Technology (IIIT), Hyderabad",
  "BITS Pilani, Hyderabad Campus",
  "Chaitanya Bharathi Institute of Technology (CBIT), Hyderabad",
  "VNR Vignana Jyothi Institute of Engineering and Technology (VNRVJIET)",
  "Vasavi College of Engineering, Hyderabad",
  "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET)",
  "Maturi Venkata Subba Rao (MVSR) Engineering College",
  "C.V.R. College of Engineering, Ibrahimpatnam",
  "Vardhaman College of Engineering, Shamshabad",
  "Mahatma Gandhi Institute of Technology (MGIT), Hyderabad",
  "BVRIT Hyderabad College of Engineering for Women",
  "BVRIT Narsapur (Padmasri Dr. B.V. Raju Institute of Technology)",
  "Keshav Memorial Institute of Technology (KMIT), Hyderabad",
  "Anurag University, Ghatkesar",
  "SR University, Warangal",
  "Mahindra University, Hyderabad",
  "Woxsen University, Sangareddy",
  "Muffakham Jah College of Engineering and Technology (MJCET)",
  "Lords Institute of Engineering and Technology, Hyderabad",
  "Stanley College of Engineering and Technology for Women",
  "Kakatiya Institute of Technology and Science (KITS), Warangal",
  "G. Narayanamma Institute of Technology and Science (GNITS)",
  "Sreenidhi Institute of Science and Technology (SNIST), Ghatkesar",
  "JNTUH College of Engineering, Jagtial",
  "JNTUH College of Engineering, Manthani",
  "JNTUH College of Engineering, Sultanpur",
  "University College of Engineering (OU), Hyderabad",
  "Matrusri Engineering College, Saidabad",
  "Methodist College of Engineering and Technology, Abids",
  "Deccan College of Engineering and Technology, Hyderabad",
  "TKR College of Engineering and Technology, Meerpet",
  "Geethanjali College of Engineering and Technology, Keesara",
  "Vidya Jyothi Institute of Technology (VJIT), Moinabad",
  "Guru Nanak Institutions Technical Campus, Ibrahimpatnam",
  "CMR College of Engineering & Technology, Kandlakoya",
  "CMR Institute of Technology (CMRIT), Hyderabad",
  "CMR Technical Campus, Kandlakoya",
  "St. Martin's Engineering College, Secunderabad",
  "Malla Reddy College of Engineering and Technology (MRCET)",
  "Malla Reddy Engineering College (MREC), Maisammaguda",
  "Malla Reddy Institute of Technology and Science",
  "Bharat Institute of Engineering and Technology, Ibrahimpatnam",
  "Sridevi Women's Engineering College, Vattinagulapally",
  "Gyan Ganga Institute of Technology",
  "Kakatiya University, Warangal",
  "Palamuru University, Mahabubnagar",
  "Mahatma Gandhi University, Nalgonda",
  "Telangana University, Nizamabad",
  "Satavahana University, Karimnagar"
].sort();
